[versions]
java = "21"
spring-boot = "3.3.5"
spring-dep-mgmt = "1.1.6"
netty = "4.1.115.Final"
jackson = "2.18.1"
junit = "5.11.3"
assertj = "3.26.3"
slf4j = "2.0.16"
json-schema-validator = "1.5.2"

[libraries]
netty-all             = { module = "io.netty:netty-all", version.ref = "netty" }
jackson-databind      = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-jsr310        = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
slf4j-api             = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
junit-bom             = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter         = { module = "org.junit.jupiter:junit-jupiter" }
assertj-core          = { module = "org.assertj:assertj-core", version.ref = "assertj" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "json-schema-validator" }

[plugins]
spring-boot     = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dep-mgmt = { id = "io.spring.dependency-management", version.ref = "spring-dep-mgmt" }